require 'rails_helper'

describe WithPassword do

  describe '.new' do

    let(:model){ OpenStruct.new(a_method: 'RESULT', encrypted_password: nil) }
    subject{ described_class.new(model) }

    it 'returns an intance with all the methods of the model given as agument' do
      expect(subject.a_method).to eq 'RESULT'
    end

    it 'adds a password method with an autogenerated password' do
      expect(subject.password.length).to be > 0
    end

    it 'saves the encrypted password in encrypted_password' do
      expect(subject.encrypted_password).to eq Encryptor.new.encrypt(subject.password)
    end

  end

end
